---
title: The Grammar of Graphics 
subtitle: "[[ANU BDSI<br>workshop]{.tag-label} Data Visualisation with R [Part 1]{.part-label}]{.tag-workshop}"
format:
  anu-light-revealjs:
    width: 1920
    height: 1080
    auto-stretch: false
    html-math-method: katex
    self-contained: true
    css: 
     - assets/custom.css
     - assets/table.css
    footer: anu-bdsi.github.io/workshop-data-vis-R1/
author: Emi Tanaka
institute: Biological Data Science Institute
date: 2024/04/10
date-format: "D[th] MMMM YYYY"
engine: knitr
---


# Welcome 👋

```{r}
#| include: false
library(tidyverse)
source("setup.R")
```

## Teaching team 


`r photo_path <- ""`

{{< include _team.qmd >}}

# Workshop materials

::: box

All materials will be hosted at<br> [<https://anu-bdsi.github.io/workshop-data-vis-R1/>]{.f-subheadline target="_blank"}

:::

## 🕙 Schedule

```{r}
#| echo: false
ex_tabset <- function(id) {
  paste0("_Exercise ", id, "_")
}

slide_title <- function(id) {
 paste0("**", rmarkdown::yaml_front_matter(paste0("slide", id, ".qmd"))$title, "**")
}

start <- dmy_hms("03/04/2024 10.00.00")
timedisplay <- function(duration) {
  end <- start + duration(duration, units = "minutes")
  ret <- paste0(format(start, "%H:%M"), "--", format(end, "%H:%M"))
  start <<- end
  ret
}

content |> 
  rowwise() |> 
  mutate(Time = timedisplay(time)) |> 
  mutate(Content = switch(type,
                              "exercise" = ex_tabset(content_id),
                              "slide" = slide_title(content_id),
                              "break" = "_Break_")) |>
  select(Time, Content) |> 
  knitr::kable()
```


## Today's learning objectives 

```{r, include = FALSE}
library(tidyverse)
source("setup.R")
```


```{r}
#| results: asis 
#| echo: false
learning_objectives()
```



## {{< fa crosshairs >}} Current learning objective


```{r}
#| results: asis 
#| echo: false
learning_objectives(1)
```



## Summary


# Exercise time {background-color="#F5EDDE"}


[<i class='fas fa-laptop-code'></i>](https://anu-bdsi.github.io/workshop-intro-R/materials.html#tabset-1-1-tab){.f-headline}

`r exercise_countdown(1)`

